<?php

namespace Container7pGMoa3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XZH8sqJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xZH8sqJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xZH8sqJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AppController::number' => ['privates', '.service_locator.TcRu_Tg', 'get_ServiceLocator_TcRuTgService', true],
            'App\\Controller\\MakeAnnonce::userMakeAnnonce' => ['privates', '.service_locator.CFHKh3Q', 'get_ServiceLocator_CFHKh3QService', true],
            'App\\Controller\\PageController::infojob' => ['privates', '.service_locator.d4rjvn4', 'get_ServiceLocator_D4rjvn4Service', true],
            'App\\Controller\\PageController::uploadVideo' => ['privates', '.service_locator.g6H.xPr', 'get_ServiceLocator_G6H_XPrService', true],
            'App\\Controller\\SingController::sinIn' => ['privates', '.service_locator.D4VetXp', 'get_ServiceLocator_D4VetXpService', true],
            'App\\Controller\\SingController::sinUp' => ['privates', '.service_locator.jRJhN5b', 'get_ServiceLocator_JRJhN5bService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\AppController:number' => ['privates', '.service_locator.TcRu_Tg', 'get_ServiceLocator_TcRuTgService', true],
            'App\\Controller\\MakeAnnonce:userMakeAnnonce' => ['privates', '.service_locator.CFHKh3Q', 'get_ServiceLocator_CFHKh3QService', true],
            'App\\Controller\\PageController:infojob' => ['privates', '.service_locator.d4rjvn4', 'get_ServiceLocator_D4rjvn4Service', true],
            'App\\Controller\\PageController:uploadVideo' => ['privates', '.service_locator.g6H.xPr', 'get_ServiceLocator_G6H_XPrService', true],
            'App\\Controller\\SingController:sinIn' => ['privates', '.service_locator.D4VetXp', 'get_ServiceLocator_D4VetXpService', true],
            'App\\Controller\\SingController:sinUp' => ['privates', '.service_locator.jRJhN5b', 'get_ServiceLocator_JRJhN5bService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\AppController::number' => '?',
            'App\\Controller\\MakeAnnonce::userMakeAnnonce' => '?',
            'App\\Controller\\PageController::infojob' => '?',
            'App\\Controller\\PageController::uploadVideo' => '?',
            'App\\Controller\\SingController::sinIn' => '?',
            'App\\Controller\\SingController::sinUp' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AppController:number' => '?',
            'App\\Controller\\MakeAnnonce:userMakeAnnonce' => '?',
            'App\\Controller\\PageController:infojob' => '?',
            'App\\Controller\\PageController:uploadVideo' => '?',
            'App\\Controller\\SingController:sinIn' => '?',
            'App\\Controller\\SingController:sinUp' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
