<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7pGMoa3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7pGMoa3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7pGMoa3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7pGMoa3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7pGMoa3\App_KernelDevDebugContainer([
    'container.build_hash' => '7pGMoa3',
    'container.build_id' => '2f540850',
    'container.build_time' => 1633729948,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7pGMoa3');
