<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWXz5Nsi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWXz5Nsi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWXz5Nsi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWXz5Nsi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWXz5Nsi\App_KernelDevDebugContainer([
    'container.build_hash' => 'WXz5Nsi',
    'container.build_id' => 'd7cd507b',
    'container.build_time' => 1649709283,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWXz5Nsi');
