<?php

namespace ContainerWXz5Nsi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_YJ7s0c2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.yJ7s0c2' shared service.
     *
     * @return \App\Script\SessionAndCookies
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\AppController::number()": the $userScript argument is type-hinted with the non-existent class or interface: "App\\Script\\SessionAndCookies".');
    }
}
