<?php

namespace ContainerWXz5Nsi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TcRuTgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TcRu_Tg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TcRu_Tg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'userScript' => ['privates', '.errored.yJ7s0c2', NULL, 'Cannot determine controller argument for "App\\Controller\\AppController::number()": the $userScript argument is type-hinted with the non-existent class or interface: "App\\Script\\SessionAndCookies".'],
        ], [
            'userScript' => '?',
        ]);
    }
}
