<?php

namespace ContainerWXz5Nsi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JRJhN5bService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jRJhN5b' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jRJhN5b'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'userScript' => ['privates', 'App\\Script\\UserInformationScript', 'getUserInformationScriptService', true],
        ], [
            'userScript' => 'App\\Script\\UserInformationScript',
        ]);
    }
}
