<?php

namespace ContainerWXz5Nsi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMakeAnnonceScriptService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Script\MakeAnnonceScript' shared autowired service.
     *
     * @return \App\Script\MakeAnnonceScript
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Script/MakeAnnonceScript.php';

        return $container->privates['App\\Script\\MakeAnnonceScript'] = new \App\Script\MakeAnnonceScript();
    }
}
